name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ecs-static-site .
          docker tag ecs-static-site:latest $ECR_REPO:latest

      - name: Push to ECR
        run: |
          docker push $ECR_REPO:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="rds_password=${{ secrets.RDS_PASSWORD }}" -var="rds_username=${{ secrets.RDS_USERNAME }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="rds_password=${{ secrets.RDS_PASSWORD }}" -var="rds_username=${{ secrets.RDS_USERNAME }}"
